[package]
name = "stream-service"
version = "0.1.0"
edition = "2021"

[dependencies]

tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.10"
axum = "0.8.4"
mpsc = "0.2.6"
oneshot = "0.1.11"
bytes = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
